version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-cli-node-browsers
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2.2-always-
            - npm-v2.3-{{ checksum "gatsby/package-lock.json" }}
      - run:
          name: Install rsync
          command: |
            sudo apt install -y rsync
      - run:
          name: Install Terminus
          command: |
            cd ~/
            curl -O https://raw.githubusercontent.com/alexfornuto/terminus-installer/master/installer.php
            php installer.php
      - run:
          name: Install Gatsby
          command: |
            cd ~/build/gatsby
            sudo npm install -g gatsby
            npm install
      - run:
          name: Import GitHub Token
          command: |
            cd ~/build/gatsby
            touch .env.production
            echo "GITHUB_API=$GITHUB_TOKEN" > .env.production
      - run:
          name: Gatsby Build
          command: |
            cd ~/build/gatsby
            gatsby build --prefix-paths
      - run:
          name: Remove empty directories
          command: |
            find ~/build/gatsby/public -type d -empty -delete
      - run:
          name: Deploy Multidev environment
          command: |
            bash ./scripts/deploy-multidev.sh
      - save_cache:
          key: npm-v2.3-{{ checksum "gatsby/package-lock.json" }}
          paths:
            - ~/build/gatsby/package-lock.json
            - ~/build/gatsby/node_modules
      - save_cache:
          key: v2.2-always-{{ epoch }}
          paths:
            - ~/build/gatsby/public
            - ~/build/gatsby/.cache
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scripts/deploy-live.sh
            fi


# Below is CircleCI 1.0 Config Syntax that is still supported on CircleCI 2.0
experimental:
  notify:
    branches:
      only:
        - master
