version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
            - composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: Prep Environment
          command: |
            cd /home/circleci/build/gatsby
            npm install
      - run:
          name: Gatsby Generate
          command: |
            cd /home/circleci/build/gatsby
            ./node_modules/gatsby/dist/bin/gatsby.js build
      - run:
          name: Deploy Multidev environment
          command: bash ./scripts/deploy-multidev.sh
      - run:
          name: Start Ghost Driver
          command: phantomjs --webdriver=8643
          background: true
      - run:
          name: Start Gatsby
          command: |
            cd /home/circleci/build/gatsby
            ./node_modules/gatsby/dist/bin/gatsby.js develop
          background: true
      - run:
          name: Wait for Gatsby
          command: dockerize -wait tcp://localhost:8000 -timeout 1m
      - run:
          name: Behat
          command: |
            /documentation/bin/behat
      - run:
          name: a11y
          command: |
            /documentation/node_modules/.bin/grunt test
      - run:
          name: Merge Conflicts
          command: |
            scripts/merge_conflicts.sh
      - run:
          name: htmlProofer
          command: |
            htmlproofer --assume-extension  ./output_prod/ --disable-external true
      - run:
          name: Speedtest
          command: |
            echo
            # Run sitespeed.io performance testing.
            mkdir ~/build/artifacts
            bash scripts/run-sitespeed-test.sh
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/build/node_modules
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ~/.composer/cache
      - store_artifacts:
          path: ~/build/sitespeed-result

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scripts/deploy-live.sh
            fi


# Below is CircleCI 1.0 Config Syntax that is still supported on CircleCI 2.0
experimental:
  notify:
    branches:
      only:
        - master
